### ISSUE TITLE
License inconsistencies

### ISSUE THREAD

**Issue by cinemast** [lvc/abi-monitor#2]
Hi Andrey!

There are some license inconsistencies. The header of your source files declare GPL or Lesser GPL. The statement is missing a version or a minimal version.

The LICENSE file mentions GPL-2 or Library GPL-2. 

Could you please clarify this?

**Comment by aponomarenko** [comment]
Hi Peter,

GPL2+ or LGPL2+

I will correct the header soon.

Thank you.

**Comment by lvc** [comment]
It's LGPL2.1+ for now.
